services:
  postgres:
    image: postgres:15
    container_name: bigdataspark_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bigdataspark
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/sql
      - ./data:/data
      - pg_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: bigdataspark_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      environment:
      CLICKHOUSE_DB: reports
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: postgres
    volumes:
      - ch_data:/var/lib/clickhouse

  spark:
    image: apache/spark:3.5.3
    container_name: bigdataspark_spark
    depends_on:
      - postgres
      - clickhouse
    volumes:
      - ./spark:/app
    working_dir: /app
    command: tail -f /dev/null

volumes:
  pg_data:
  ch_data:
